name: daily_wall
description: Daily wall / diary app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  flutter_quill: ^11.4.2
  path_provider: ^2.1.4
  path: ^1.9.0
  desktop_drop: ^0.6.1
  share_handler: ^0.0.25
  flutter_staggered_grid_view: ^0.7.0

  # нове — для прев'ю посилань
  http: ^1.2.2
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
